local t = Def.ActorFrame {
	Def.Actor{
		OnCommand=function(self)
			self:sleep(4.5)
		end;
	};
	LoadActor("RING.png")..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:visible(true):blend('BlendMode_Add'):diffusealpha(0.6):zoom(1.2):linear(0.4):zoom(0.8):diffusealpha(0)
		end;
	};
	LoadActor("DECIDE_FRAME1.png")..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y-65):zoomtowidth(SCREEN_WIDTH)
		end;
		OnCommand=function(self)
			self:visible(true):addx(10):addy(10):diffusealpha(0):sleep(.5):linear(.2):addx(-10):addy(-10):diffusealpha(.8):sleep(1.4):linear(.1):addy(-10):linear(.1):addx(-10)
		end;
	};
	LoadActor("DECIDE_FRAME1.png")..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y-65):zoomtowidth(SCREEN_WIDTH)
		end;
		OnCommand=function(self)
			self:visible(true):blend('BlendMode_Add'):diffusealpha(0):sleep(.8):diffusealpha(1):sleep(0.05):diffusealpha(0):sleep(1.15):diffusealpha(1):sleep(.05):diffusealpha(0)
		end;
	};
	LoadActor("DECIDE_FRAME2.png")..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y+65):zoomtowidth(SCREEN_WIDTH)
		end;
		OnCommand=function(self)
			self:visible(true):addx(-10):addy(-10):diffusealpha(0):sleep(.5):linear(.2):addx(10):addy(10):diffusealpha(.8):sleep(1.4):linear(.1):addy(10):linear(.1):addx(10)
		end;
	};
	LoadActor("DECIDE_FRAME2.png")..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y+65):zoomtowidth(SCREEN_WIDTH)
		end;
		OnCommand=function(self)
			self:visible(true):blend('BlendMode_Add'):diffusealpha(0):sleep(.9):diffusealpha(1):sleep(0.05):diffusealpha(0):sleep(1.05):diffusealpha(1):sleep(.05):diffusealpha(0)
		end;
	};
	LoadActor("RING.png")..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y)
		end;
		OnCommand=function(self)
			self:visible(true):blend('BlendMode_Add'):diffusealpha(0.6):zoom(3):linear(.2):zoom(2):linear(0.15):zoom(1):diffusealpha(0)
		end;
	};
	LoadActor("RING.png")..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y-5)
		end;
		OnCommand=function(self)
			self:visible(true):blend('BlendMode_Add'):diffusealpha(.6):zoom(0):sleep(0.6):linear(0.2):zoom(1):sleep(1.4):linear(0.3):diffusealpha(0)
		end;
	};
	LoadActor("DECISION.png")..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y-5)
		end;
		OnCommand=function(self)
			self:visible(true):cropright(1):sleep(2.2):linear(.3):cropright(0)
		end;
	};
	Def.Quad{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y):zoomtowidth(SCREEN_WIDTH):zoomtoheight(SCREEN_HEIGHT):diffuse(color("#ffffff"))
		end;
		OnCommand=function(self)
			self:visible(true):diffuse(0,0,0,1):diffusealpha(0):sleep(2.6):linear(.3):diffusealpha(1)
		end;
	};
	Def.Quad{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y):zoomtowidth(SCREEN_WIDTH):zoomtoheight(SCREEN_HEIGHT):diffuse(color("#ffffff"))
		end;
		OnCommand=function(self)
			self:visible(true):linear(0.4):diffusealpha(0):blend('BlendMode_Add')
		end;
	};
};
return t;