local t = Def.ActorFrame {
	LoadActor("solo.png")..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X):y(SCREEN_CENTER_Y-10)
		end;
		OnCommand=function(self)
			self:zoom(0):bounceend(0.35):zoom(1)
		end;
		GainFocusCommand=function(self)
			self:stoptweening()
		end;
		LoseFocusCommand=function(self)
			self:stoptweening()
		end;
		DisabledCommand=function(self)
			self:diffusealpha(0)
		end;
		EnabledCommand=function(self)
			self:diffusealpha(1)
		end;
	};
	LoadActor("cursor-dance.png")..{
		InitCommand=function(self)
			self:blend('BlendMode_Add'):x(SCREEN_CENTER_X-1):y(SCREEN_CENTER_Y-10)
		end;
		OnCommand=function(self)
			self:diffusealpha(0)
		end;
		GainFocusCommand=function(self)
			self:stoptweening():diffusealpha(1)
		end;
		LoseFocusCommand=function(self)
			self:stoptweening():diffusealpha(0)
		end;
		DisabledCommand=function(self)
			self:diffusealpha(0)
		end;
		EnabledCommand=function(self)
			self:diffusealpha(1)
		end;
	};
};

return t;